# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [1]:
#list(a)：若是多維陣列，只會將第一層轉成list，剩下的會維持原本的型態
#tolist(a)：確實將每一層陣列轉換為list

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [2]:
# 記得先 Import 正確的套件
import numpy as np

In [3]:
a = np.random.randint(10, size=6) 

print(a) #建立一個一維陣列，陣列大小是6，裡面的每個值：從數字0~9，隨機取出6個數字(可重複)
print(a.ndim) #陣列有多少維度：1維
print(a.shape) #每個維度的大小：6
print(a.size) #陣列當中有幾個元素：6
print(a.dtype) #陣列中的資料型態：int32
print(a.itemsize) #陣列中每個元素佔用的空間：4 byte
print(len(a)) #回傳第一層陣列的長度：6
print(type(a)) #回傳 a 元素的資料型態：numpy.ndarray，即 numpy 的多維陣列型態

[2 6 8 5 9 5]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [4]:
b = np.random.randint(10, size=(3,4)) 

print(b) #建立一個二維陣列，陣列大小是3x4，裡面的每個值：從數字0~9，隨機取出數字(可重複)
print(b.ndim) #陣列有多少維度：2維
print(b.shape) #每個維度的大小：第一維是 3，第二維是 4
print(b.size) #陣列當中有幾個元素：12
print(b.dtype) #陣列中的資料型態：int32
print(b.itemsize) #陣列中每個元素佔用的空間：4 byte
print(len(b)) #回傳第一層陣列的長度：3
print(type(b)) #回傳 b 元素的資料型態：numpy.ndarray，即 numpy 的多維陣列型態

[[1 7 4 9]
 [6 6 2 1]
 [2 2 6 8]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [5]:
c = np.random.randint(10, size=(2,3,2)) 

print(c) #建立一個三維陣列，陣列大小是2x3x2，裡面的每個值：從數字0~9，隨機取出數字(可重複)
print(c.ndim) #陣列有多少維度：3維
print(c.shape) #每個維度的大小：第一維是 2，第二維是 3，第三維是 2
print(c.size) #陣列當中有幾個元素：12
print(c.dtype) #陣列中的資料型態：int32
print(c.itemsize) #陣列中每個元素佔用的空間：4 byte
print(len(c)) #回傳第一層陣列的長度：2
print(type(c)) #回傳 c 元素的資料型態：numpy.ndarray，即 numpy 的多維陣列型態

[[[5 9]
  [2 4]
  [5 2]]

 [[4 6]
  [3 6]
  [7 0]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [6]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[4, 8, 5, 6, 7, 7]
[4, 8, 5, 6, 7, 7]


In [7]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[6, 1, 9, 9], [4, 2, 3, 7], [6, 4, 2, 4]]
[array([6, 1, 9, 9]), array([4, 2, 3, 7]), array([6, 4, 2, 4])]


In [8]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[3, 5], [5, 7], [5, 5]], [[4, 8], [7, 3], [1, 1]]]
[array([[3, 5],
       [5, 7],
       [5, 5]]), array([[4, 8],
       [7, 3],
       [1, 1]])]


In [9]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    nlist = []
    for item in iterable:
        nlist.append(tolist(item))
    return nlist
        

print(tolist(a))
print(tolist(b))
print(tolist(c))

[4, 8, 5, 6, 7, 7]
[[6, 1, 9, 9], [4, 2, 3, 7], [6, 4, 2, 4]]
[[[3, 5], [5, 7], [5, 5]], [[4, 8], [7, 3], [1, 1]]]
