# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [1]:
import numpy as np
a = np.arange(10).reshape(2,5)
print(a.sum()) #對 a 整個陣列加總
print(np.sum(a)) #對 a 陣列的每一個值加總
print(sum(a)) #對 axis=0 的每一個值加總

45
45
[ 5  7  9 11 13]


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [2]:
# 記得先 Import 正確的套件
import numpy as np

In [3]:
A = np.random.random((5, 5))

normalization = (A - np.min(A)) / (np.max(A) - np.min(A))
normalization

array([[0.82223341, 0.85926418, 0.7443018 , 0.20164818, 0.89390459],
       [0.91028184, 0.01955315, 1.        , 0.06730752, 0.68994708],
       [0.20561577, 0.88533246, 0.98839345, 0.54703604, 0.05924427],
       [0.76989238, 0.        , 0.54629724, 0.46157746, 0.03256709],
       [0.11449159, 0.19624646, 0.76961674, 0.43107928, 0.60638822]])

### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [4]:
A = np.arange(10)
A[np.amax(A)] = -1
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, -1])